<a href="https://colab.research.google.com/github/angelarwa/TIL/blob/master/tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 12월30일

In [0]:
import tensorflow as tf

print(tf.__version__) 

#activate tutorial

1.15.0


In [0]:
import tensorflow as tf

#상수(constant) 정의
a = tf.constant(1234) 
b = tf.constant(5000)

#계산 정의
add_op = a+b

#세션 시작 
sess = tf.Session() 
res = sess.run(add_op) #계산식 평가 
print(res)

6234


In [0]:
import tensorflow as tf

#상수 정의
a = tf.constant(2) 
b = tf.constant(3)
c = tf.constant(4)

#계산 정의
calc1_op = a + b *c
calc2_op = (a+b) * c

#세션 시작 
sess = tf.Session() 
res1 = sess.run(calc1_op) #계산식 평가 
print(res1)
res2 = sess.run(calc2_op) #계산식 평가 
print(res2)


14
20


In [0]:
import tensorflow as tf

#상수 정의
a = tf.constant(100) 
b = tf.constant(50)
add_op = a+ b

#변수 v 선언하기
v = tf.Variable(0)

# 변수 v에 add_op의 결과 대입하기
let_op = tf.assign(v, add_op)

#세션 시작 
sess = tf.Session() 
# 변수 초기화히기
sess.run(tf.global_variables_initializer()) 
#계산식 실행
sess.run(let_op) 
print(sess.run(v))

150


In [0]:
import tensorflow as tf

a = tf.placeholder(tf.int32, [3]) #placeholder 정의(정수 자료형 3개를 가진 배열)
b = tf.constant(2)
x2_op = a*b

#세션 시작 
sess = tf.Session() 
# placeholder에 값 넣고 실행하기
r1 = sess.run(x2_op, feed_dict = {a:[1, 2, 3]})
print(r1)
r2 = sess.run(x2_op, feed_dict = {a:[10, 20, 10]})
print(r2)

#tensoflow.sqrt(x): x의 제곱근을 계산
#tensoflow.reduce_mean(x): x의 평균을 계산
#tensoflow.square(x): x의 제곱을 계산
#random_uniform([1], 0, 10,…) : 0에서 10 사이에서 임의의 수 1개 생성 반환
#Variable() : 변수의 값을 지정 

[2 4 6]
[20 40 20]


In [0]:
import tensorflow as tf

#placeholder 정의(배열의 크기를 None으로 지정)
a = tf.placeholder(tf.int32, [None]) 
b = tf.constant(10) #b를 상수 10이라고 정의
x10_op = a*b

#세션 시작 
sess = tf.Session() 
# placeholder에 값 넣고 실행하기
r1 = sess.run(x10_op, feed_dict = {a:[1, 2, 3, 4, 5]}) #b=10
print(r1)
r2 = sess.run(x10_op, feed_dict = {a:[10, 20]})
print(r2)

[10 20 30 40 50]
[100 200]


In [0]:
#SVM으로 BMI 판정
#키의 최대값은 200cm, 몸무게의 최대값은 100kg으로 정규화
#저체중(thin), 정상(normal), 비만(fat) 레이블을 one-hot-encoding [1, 0, 0], [0, 1, 0], [0, 0, 1]로 변환
#소프트 맥스 회귀방법 , 오차 함수는 교차 엔트로피 사용
#교차 엔트로피  - 2개의 확률 분포 사이에 정의되는 척도로서 교차 엔트로피 값이 작을 수록 정확한 값을 냄
#학습 계수 0.01, 경사 하강법(steepest descent method) 사용

import pandas as pd
import numpy as np
import tensorflow as tf
# 키, 몸무게, 레이블이 적힌 CSV 파일 읽어 들이기 
csv = pd.read_csv("bmi.csv")

# 데이터 정규화 
csv["height"]=csv["height"]/200
csv["weight"]=csv["weight"]/100

# 레이블을 배열로 변환하기 - thin=(1,0,0) / normal=(0,1,0) / fat=(0,0,1)
bclass={"thin":[1,0,0],"normal":[0,1,0],"fat":[0,0,1]}
csv["label_pat"]=csv["label"].apply(lambda x: np.array(bclass[x]))

# 테스트를 위한 데이터 분류 
test_csv=csv[15000:20000]
tset_pat=test_csv[["weight","height"]]
test_ans=list(test_csv["label_pat"])
    
# 데이터 플로우 그래프 구축하기 
# 플레이스홀더 선언하기
x=tf.placeholder(tf.float32,[None,2])#키와 몸무게 데이터 넣기
y_=tf.placeholder(tf.float32, [None,3])#정답 레이블 넣기
 
# 변수 선언하기 
W=tf.Variable(tf.zeros([2,3]));#가중치
b=tf.Variable(tf.zeros([3]));#바이어스
 
# 소프트맥스 회귀 정의하기 
y=tf.nn.softmax(tf.matmul(x,W)+b)
    
# 모델 훈련하기 
cross_entropy=
optimizer=
train=
 
# 정답률 구하기
predict=
accuracy=
 
# 세션 시작하기
session 
? 
 
# 학습시키기
for step in range(3500):

# 최종적인 정답률 구하기
 


SyntaxError: invalid syntax (<ipython-input-16-d81df39ff66d>, line 40)

## tensorboard

In [0]:
#데이터의 흐름을 시각화하는 도구
#로그 데이터를 저장할 폴더 준비 
#tensorboard --logdir=/log_dir
#Localhost:6006   

import tensorflow as tf
a = tf.constant(20, name="a")# 데이터 플로우 그래프 구축하기  
b = tf.constant(30, name="b")
mul_op = a * b
sess = tf.Session() #세션 생성하기  
tw = tf.summary.FileWriter("log_dir", graph=sess.graph)# TensorBoard 사용하기  
print(sess.run(mul_op))# 세션 실행하기 

600


In [0]:
import tensorflow as tf
# 상수와 변수 선언하기  
a = tf.constant(100, name="a")
b = tf.constant(200, name="b")
c = tf.constant(300, name="c")
v = tf.Variable(0, name="v")
# 곱셈을 수행하는 그래프 정의하기  
calc_op = a + b * c 
assign_op = tf.assign(v, calc_op)
# 세션 생성하기  
sess = tf.Session()
# TensorBoard 사용하기  
tw = tf.summary.FileWriter("log_dir", graph=sess.graph)
# 세션 실행하기   
sess.run(assign_op)
print(sess.run(v))


60100


## 최소 제곱법 공식으로 구한 성적 예측 코딩   

In [0]:
import numpy as np

# x 값과 y 값
x=[2,4,6,8]
y=[81,93,91,97]

# x와 y의 평균값
mx=np.mean(x)
my=np.mean(y)
print("x의 평균값:",mx)
print("y의 평균값:",my)

# 기울기 공식의 분모
divisor=sum([(mx-i)**2 for i in x])

# 기울기 공식의 분자
def top(x,mx,y,my):
    d=0
    for i in range(len(x)):
        d+=(x[i]-mx)*(y[i]-my)
    return d
dividend=top(x,mx,y,my) #분자값 게산 저장
print("분모",divisor)
print("분자",dividend)
    
# 기울기와 y 절편 구하기
a=dividend/divisor
b=my-(mx*a)

# 출력으로 확인
print("기울기 a=",a)
print("y절편 b=",b)

x의 평균값: 5.0
y의 평균값: 90.5
분모 20.0
분자 46.0
기울기 a= 2.3
y절편 b= 79.0


## 오차 계산 : 평균 제곱근 오차(root mean square error)

In [0]:
import numpy as np

# 기울기 a와 y 절편 b
ab = [3, 76] #  임의의 기울기와 절편
data = [[2,81],[4,93],[6,91],[8,97]]

# x, y의 데이터 값
x= [ i[0] for i in data]
y= [ i[1] for i in data]

# y = ax + b에 a와 b 값을 대입하여 결과를 출력하는 함수
def predict(x): #임의의 기울기와 절편의 모델로부터 예측값 반환 함수
    return ab[0]*x+ab[1]

# RMSE 함수
def rmse(p, a): # 평균 제곱근 오차 반환 함수
    return np.sqrt(((p-a)**2).mean())
 

# RMSE 함수를 각 y 값에 대입하여 최종 값을 구하는 함수
 

# 예측 값이 들어갈 빈 리스트
predict_result = []

for i in range(len(x)):
    predict_result.append(predict(x[i]))
print("공부한 시간 =%.f, 실제 점수 =%.f,  예측점수=%.f" % (x[i], y[i], predict_result[i]))



# 모든 x 값을 한 번씩 대입하여
 
# 평균 제곱근 오차 반환 함수를 이용해서 최종값 구하기
def  rmse_val(predict_result, y) :
    return rmse(np.array(predict_result), np.array(y))


# 최종 RMSE 출력
print("rmse  최종값 :"+ str(rmse_val(predict_result, y)))

공부한 시간 =8, 실제 점수 =97,  예측점수=100
rmse  최종값 :3.3166247903554


## 경사하강법 : 미분값이 0인 기울기와 y절편 찾기 (학습률 지정) 

In [0]:
import tensorflow as tf

data = [[2,81],[4,93],[6,91],[8,97]]

# x 값과 y 값
x_data= [ i[0] for i in data]
y_data= [ i[1] for i in data]

#임의의 기울기와 y절편의 값으로 변수로 정의
a=tf.Variable(tf.random_uniform([1], 0, 10, dtype=tf.float64, seed=0))   #기울기 범위 0~10
b = tf.Variable(tf.random_uniform([1], 0, 100, dtype=tf.float64, seed=0))   #y절편 범위 0~100

y = a*x_data+b  #1차방정식의 계산식 정의

#오차 계산 (평균 제곱근 오차 공식)
rmse = tf.sqrt(tf.reduce_mean(tf.square(y-y_data)))

#학습률
learning_rate = 0.1

# 오차 rmse 값이 최소인 값 찾는 식 정의
gradient_descent = tf.train.GradientDescentOptimizer(learning_rate).minimize(rmse)

#텐서플로으로 학습
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())     # 변수들을 메모리에 생성, 초기화
    for step in range(2001):
        sess.run(gradient_descent)
        if step % 100 == 0:
            print("Epoch: %.f , RMSE=%.4f,  기울기 a=%.4f, 절편 b= %.4f" % (step, sess.run(rmse), sess.run(a), sess.run(b)))

#Epoch는 입력값에 대해 몇 번 반복 실험했는지를 나타내는 용어

Epoch: 0 , RMSE=30.2139,  기울기 a=7.5235, 절편 b= 80.5984
Epoch: 100 , RMSE=2.8860,  기울기 a=2.2299, 절편 b= 79.4181
Epoch: 200 , RMSE=2.8826,  기울기 a=2.2601, 절편 b= 79.2379
Epoch: 300 , RMSE=2.8815,  기울기 a=2.2773, 절편 b= 79.1353
Epoch: 400 , RMSE=2.8811,  기울기 a=2.2871, 절편 b= 79.0770
Epoch: 500 , RMSE=2.8810,  기울기 a=2.2927, 절편 b= 79.0438
Epoch: 600 , RMSE=2.8810,  기울기 a=2.2958, 절편 b= 79.0249
Epoch: 700 , RMSE=2.8810,  기울기 a=2.2976, 절편 b= 79.0142
Epoch: 800 , RMSE=2.8810,  기울기 a=2.2987, 절편 b= 79.0081
Epoch: 900 , RMSE=2.8810,  기울기 a=2.2992, 절편 b= 79.0046
Epoch: 1000 , RMSE=2.8810,  기울기 a=2.2996, 절편 b= 79.0026
Epoch: 1100 , RMSE=2.8810,  기울기 a=2.2998, 절편 b= 79.0015
Epoch: 1200 , RMSE=2.8810,  기울기 a=2.2999, 절편 b= 79.0008
Epoch: 1300 , RMSE=2.8810,  기울기 a=2.2999, 절편 b= 79.0005
Epoch: 1400 , RMSE=2.8810,  기울기 a=2.3000, 절편 b= 79.0003
Epoch: 1500 , RMSE=2.8810,  기울기 a=2.3000, 절편 b= 79.0002
Epoch: 1600 , RMSE=2.8810,  기울기 a=2.3000, 절편 b= 79.0001
Epoch: 1700 , RMSE=2.8810,  기울기 a=2.3000, 절편 b= 79.0001
Epo

In [0]:
#경사하강법 : 다중회귀분석 실습
import tensorflow as tf 

data = [[2,0, 81],[4,4, 93],[6,2,91],[8,3,97]]
# x 값과 y 값
x1= [ i[0] for i in data]
x2= [ i[1] for i in data]
y_data= [ i[2] for i in data]


#임의의 기울기와 y절편의 값으로 변수로 정의
a1=tf.Variable(tf.random_uniform([1], 0, 10, dtype=tf.float64, seed=0))   #기울기 범위 0~10
a2=tf.Variable(tf.random_uniform([1], 0, 10, dtype=tf.float64, seed=0))   #기울기 범위 0~10
b = tf.Variable(tf.random_uniform([1], 0, 100, dtype=tf.float64, seed=0))   #y절편 범위 0~100

y = a1*x1+a2*x2+b  # 입력값이 2개인 1차방정식의 계산식 정의

#오차 계산 (평균 제곱근 오차 공식)
rmse = tf.sqrt(tf.reduce_mean(tf.square(y-y_data)))

#학습률
learning_rate = 0.1

# 오차 rmse 값이 최소인 값 찾는 식 정의
gradient_descent = tf.train.GradientDescentOptimizer(learning_rate).minimize(rmse)

#텐서플로 이용하여 학습
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())     # 변수들을 메모리에 생성, 초기화
    for step in range(2001):
        sess.run(gradient_descent)
        if step % 100 == 0:
            print("Epoch: %.f , RMSE=%.4f,  기울기 a1=%.4f, 기울기 a2=%.4f, 절편 b= %.4f" % (step, sess.run(rmse), sess.run(a1), sess.run(a2),sess.run(b)))



Epoch: 0 , RMSE=49.1842,  기울기 a1=7.5270, 기울기 a2=7.8160, 절편 b= 80.5980
Epoch: 100 , RMSE=1.8368,  기울기 a1=1.1306, 기울기 a2=2.1316, 절편 b= 78.5119
Epoch: 200 , RMSE=1.8370,  기울기 a1=1.1879, 기울기 a2=2.1487, 절편 b= 78.1057
Epoch: 300 , RMSE=1.8370,  기울기 a1=1.2122, 기울기 a2=2.1571, 절편 b= 77.9352
Epoch: 400 , RMSE=1.8370,  기울기 a1=1.2226, 기울기 a2=2.1607, 절편 b= 77.8636
Epoch: 500 , RMSE=1.8370,  기울기 a1=1.2269, 기울기 a2=2.1622, 절편 b= 77.8335
Epoch: 600 , RMSE=1.8370,  기울기 a1=1.2288, 기울기 a2=2.1628, 절편 b= 77.8208
Epoch: 700 , RMSE=1.8370,  기울기 a1=1.2295, 기울기 a2=2.1631, 절편 b= 77.8155
Epoch: 800 , RMSE=1.8370,  기울기 a1=1.2299, 기울기 a2=2.1632, 절편 b= 77.8133
Epoch: 900 , RMSE=1.8370,  기울기 a1=1.2300, 기울기 a2=2.1632, 절편 b= 77.8124
Epoch: 1000 , RMSE=1.8370,  기울기 a1=1.2301, 기울기 a2=2.1633, 절편 b= 77.8120
Epoch: 1100 , RMSE=1.8370,  기울기 a1=1.2301, 기울기 a2=2.1633, 절편 b= 77.8118
Epoch: 1200 , RMSE=1.8370,  기울기 a1=1.2301, 기울기 a2=2.1633, 절편 b= 77.8117
Epoch: 1300 , RMSE=1.8370,  기울기 a1=1.2301, 기울기 a2=2.1633, 절편 b= 77.8117
Epo

## 로지스틱 회귀 구현 코드   

In [0]:
import tensorflow as tf
import numpy as np

# x, y의 데이터 값
data =[[2, 0], [4, 0], [6, 0], [8, 1], [10, 1], [12, 1], [14, 1]]

x_data = [i[0] for i in data]
y_data = [i[1] for i in data]


#임의의 a, b 값을 변수로 정의
a = tf.Variable(tf.random_normal([1], dtype=tf.float64, seed=0))
b = tf.Variable(tf.random_normal([1], dtype=tf.float64, seed=0))

# y 시그모이드 함수의 방정식을 세운다.
 #시그모이드 함수 방정식 정의
y = 1/ (1+ np.e**(a*x_data+b))

#오차 loss 구하는 함수
loss = -tf.reduce_mean(np.array(y_data)*tf.log(y)+(1-np.array(y_data))*tf.log(1-y))

# 학습률 값
learning_rate = 0.5

# loss를 최소로 하는 값 찾기
# 오차 rmse 값이 최소인 값 찾는 식 정의
gradient_descent = tf.train.GradientDescentOptimizer(learning_rate).minimize(loss)

#텐서플로 이용하여 학습
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())     # 변수들을 메모리에 생성, 초기화
    for step in range(6001):
        sess.run(gradient_descent)
        if step % 1000 == 0:
            print("Epoch: %.f , loss=%.4f,  기울기 a=%.4f, 절편 b= %.4f" % (step, sess.run(loss), sess.run(a), sess.run(b)))

Epoch: 0 , loss=1.2676,  기울기 a=0.1849, 절편 b= -0.4334
Epoch: 1000 , loss=0.0557,  기울기 a=-1.6009, 절편 b= 11.0208
Epoch: 2000 , loss=0.0361,  기울기 a=-2.0366, 절편 b= 14.0909
Epoch: 3000 , loss=0.0269,  기울기 a=-2.3380, 절편 b= 16.2087
Epoch: 4000 , loss=0.0214,  기울기 a=-2.5708, 절편 b= 17.8417
Epoch: 5000 , loss=0.0178,  기울기 a=-2.7607, 절편 b= 19.1734
Epoch: 6000 , loss=0.0152,  기울기 a=-2.9211, 절편 b= 20.2982


## 로지스틱 회귀분석 : 다중 입력값 , tf.sigmoid(), 

In [0]:
import tensorflow as tf 
import numpy as np

x_data = np.array( [[2,3],[4,3],[6,4],[8,6],[10, 7], [12, 8], [14, 9]] )
y_data= np.array([0, 0, 0, 1, 1, 1,1] ).reshape(7, 1)

#입력값을 placeholder에 저장
X= tf.placeholder(tf.float64, shape=[None, 2])
Y = tf.placeholder(tf.float64, shape=[None, 1])
 
#실행할 때마다 동일한 출력(결과)를 얻기 위한 값 설정
seed = 0
np.random.seed(seed)
tf.set_random_seed(seed)

#임의의 a, b 값을 변수로 정의
a = tf.Variable(tf.random_uniform([2, 1], dtype=tf.float64))  #[2, 1]은 들어오는  값은 2개 나가는 값은 1개
b = tf.Variable(tf.random_uniform([1], dtype=tf.float64))

#시그모이드 함수 방정식 정의
y = tf.sigmoid(tf.matmul(X, a) + b)

#오차 loss 구하는 함수
loss = -tf.reduce_mean(Y*tf.log(y)+(1-Y)*tf.log(1-y))

#학습률
learning_rate = 0.1

# 오차 loss 값이 최소인 값 찾는 식 정의
gradient_descent = tf.train.GradientDescentOptimizer(learning_rate).minimize(loss)

predicted = tf.cast(y >0.5, dtype=tf.float64)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float64))

#tf.cast() 함수는 형변환(캐스팅) 수행 => 부동소수점형(실수)를 정수형으로 변환할때는 소수점이하 버림
                                                    #bool (논리) 자료형을 정수형으로 변환할때는 True는 1, False는 0으로

#텐서플로 이용하여 학습
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())     # 변수들을 메모리에 생성, 초기화
    for step in range(5001):
        a_, b_, loss_, _ = sess.run([a, b, loss, gradient_descent], feed_dict={X:x_data, Y:y_data})
        if step % 500 == 0:
            print("Epoch: %.f , loss=%.4f,  기울기 a1=%.4f, 기울기 a2=%.4f, 절편 b= %.4f" % (step,  loss_,  a_[0], a_[1],  b_))

Epoch: 0 , loss=1.8561,  기울기 a1=-0.0129, 기울기 a2=0.7219, 절편 b= 0.7724
Epoch: 500 , loss=0.2118,  기울기 a1=0.8054, 기울기 a2=-0.3536, 절편 b= -3.4439
Epoch: 1000 , loss=0.1396,  기울기 a1=0.6819, 기울기 a2=0.1609, 절편 b= -5.2507
Epoch: 1500 , loss=0.1036,  기울기 a1=0.5217, 기울기 a2=0.6248, 절편 b= -6.4943
Epoch: 2000 , loss=0.0820,  기울기 a1=0.3823, 기울기 a2=1.0050, 절편 b= -7.4480
Epoch: 2500 , loss=0.0677,  기울기 a1=0.2673, 기울기 a2=1.3170, 절편 b= -8.2226
Epoch: 3000 , loss=0.0577,  기울기 a1=0.1727, 기울기 a2=1.5771, 절편 b= -8.8754
Epoch: 3500 , loss=0.0502,  기울기 a1=0.0939, 기울기 a2=1.7980, 절편 b= -9.4395
Epoch: 4000 , loss=0.0444,  기울기 a1=0.0273, 기울기 a2=1.9889, 절편 b= -9.9364
Epoch: 4500 , loss=0.0398,  기울기 a1=-0.0300, 기울기 a2=2.1564, 절편 b= -10.3804
Epoch: 5000 , loss=0.0361,  기울기 a1=-0.0798, 기울기 a2=2.3052, 절편 b= -10.7817


## 은닉층으로 좌표 평면을 왜곡시켜서 시그모이드 함수 사용해서 XOR 문제 해결

In [0]:
import tensorflow as tf 
import numpy as np

# 가중치와 바이어스
 

# 퍼셉트론
 

# NAND 게이트


# OR 게이트
 

# AND 게이트
 

# XOR 게이트
 

# x1, x2 값을 번갈아 대입해 가며 최종값 출력
 
